sudo: false
language: node_js
notifications:
  email: false
matrix:
  include:
  - node_js: "6"
  - node_js: "8"
  - node_js: "10"
before_install:
  - npm i -g npm@latest
install:
  - node --version
  - npm --version
  - npm ci
script: npm test
